saxeli = input("enter your name")
gvari = input("enter your surname")
age = input("enter your age")
height = input("enter your height")
grade = input("enter your grade")
hobby = input("enter your hobby")
academy = input("enter your acamademy")
teacher = input("enter your teacher")
print("chemi sruli saxelia {}{} da me var {} wlis chemi simaglea {} me var {} chemi hobby aris {} me vswavlob {} chemi maswavlebelia{}".format(saxeli,gvari,age,height,grade,hobby,academy,teacher))  
